;; procedure index definitions

(define proc-index 0)
(define (proc-index-inc)
  (define v proc-index)
  (set! proc-index (+ 1 proc-index))
  v)
(define make-dictionary-index (proc-index-inc))
(define dictionary?-index (proc-index-inc))
(define dict-empty?-index (proc-index-inc))
(define dict-contains?-index (proc-index-inc))
(define dict-ref-index (proc-index-inc))
(define dict-ref/default-index (proc-index-inc))
(define dict-set-index (proc-index-inc))
(define dict-set!-index (proc-index-inc))
(define dict-adjoin-index (proc-index-inc))
(define dict-adjoin!-index (proc-index-inc))
(define dict-delete-index (proc-index-inc))
(define dict-delete!-index (proc-index-inc))
(define dict-delete-all-index (proc-index-inc))
(define dict-delete-all!-index (proc-index-inc))
(define dict-replace-index (proc-index-inc))
(define dict-replace!-index (proc-index-inc))
(define dict-intern-index (proc-index-inc))
(define dict-intern!-index (proc-index-inc))
(define dict-update-index (proc-index-inc))
(define dict-update!-index (proc-index-inc))
(define dict-update/default-index (proc-index-inc))
(define dict-update/default!-index (proc-index-inc))
(define dict-pop-index (proc-index-inc))
(define dict-pop!-index (proc-index-inc))
(define dict-map-index (proc-index-inc))
(define dict-map!-index (proc-index-inc))
(define dict-filter-index (proc-index-inc))
(define dict-filter!-index (proc-index-inc))
(define dict-remove-index (proc-index-inc))
(define dict-remove!-index (proc-index-inc))
(define dict-search-index (proc-index-inc))
(define dict-search!-index (proc-index-inc))
(define dict-copy-index (proc-index-inc))
(define dict-size-index (proc-index-inc))
(define dict-for-each-index (proc-index-inc))
(define dict-count-index (proc-index-inc))
(define dict-any-index (proc-index-inc))
(define dict-every-index (proc-index-inc))
(define dict-keys-index (proc-index-inc))
(define dict-values-index (proc-index-inc))
(define dict-entries-index (proc-index-inc))
(define dict-fold-index (proc-index-inc))
(define dict-map->list-index (proc-index-inc))
(define dict->alist-index (proc-index-inc))
(define dict-comparator-index (proc-index-inc))
(define dict-procedures-count (proc-index-inc))
