(define mapping-dtd
  (let ()

    (define (prep-dtd-arg proc)
      (lambda (dtd . args)
        (apply proc args)))

    (make-dtd
     make-dictionary-index (prep-dtd-arg mapping)
     dictionary?-index (prep-dtd-arg mapping?)
     dict-empty?-index (prep-dtd-arg mapping-empty?)
     dict-contains?-index (prep-dtd-arg mapping-contains?)
     dict-ref-index (prep-dtd-arg mapping-ref)
     dict-ref/default-index (prep-dtd-arg mapping-ref/default)
     dict-set-index (prep-dtd-arg mapping-set)
     dict-set!-index (prep-dtd-arg mapping-set!)
     dict-adjoin-index (prep-dtd-arg mapping-adjoin)
     dict-adjoin!-index (prep-dtd-arg mapping-adjoin!)
     dict-delete-index (prep-dtd-arg mapping-delete)
     dict-delete!-index (prep-dtd-arg mapping-delete!)
     dict-delete-all-index (prep-dtd-arg mapping-delete-all)
     dict-delete-all!-index (prep-dtd-arg mapping-delete-all!)
     dict-replace-index (prep-dtd-arg mapping-replace)
     dict-replace!-index (prep-dtd-arg mapping-replace!)
     dict-intern-index (prep-dtd-arg mapping-intern)
     dict-intern!-index (prep-dtd-arg mapping-intern!)
     dict-update-index (prep-dtd-arg mapping-update)
     dict-update!-index (prep-dtd-arg mapping-update!)
     dict-update/default-index (prep-dtd-arg mapping-update/default)
     dict-update/default!-index (prep-dtd-arg mapping-update!/default)
     dict-pop-index (prep-dtd-arg mapping-pop)
     dict-pop!-index (prep-dtd-arg mapping-pop!)
     dict-filter-index (prep-dtd-arg mapping-filter)
     dict-filter!-index (prep-dtd-arg mapping-filter!)
     dict-remove-index (prep-dtd-arg mapping-remove)
     dict-remove!-index (prep-dtd-arg mapping-remove!)
     dict-search-index (prep-dtd-arg mapping-search)
     dict-search!-index (prep-dtd-arg mapping-search!)
     dict-copy-index (prep-dtd-arg mapping-copy)
     dict-size-index (prep-dtd-arg mapping-size)
     dict-for-each-index (prep-dtd-arg mapping-for-each)
     dict-count-index (prep-dtd-arg mapping-count)
     dict-keys-index (prep-dtd-arg mapping-keys)
     dict-values-index (prep-dtd-arg mapping-values)
     dict-entries-index (prep-dtd-arg mapping-entries)
     dict-fold-index (prep-dtd-arg mapping-fold)
     dict-map->list-index (prep-dtd-arg mapping-map->list)
     dict->alist-index (prep-dtd-arg mapping->alist)
     dict-comparator-index (prep-dtd-arg mapping-key-comparator))))
