(define hash-mapping-dtd
  (let ()

    (define (prep-dtd-arg proc)
      (lambda (dtd . args)
        (apply proc args)))

    (make-dtd
     make-dictionary-id (prep-dtd-arg hashmap)
     dictionary?-id (prep-dtd-arg hashmap?)
     dict-empty?-id (prep-dtd-arg hashmap-empty?)
     dict-contains?-id (prep-dtd-arg hashmap-contains?)
     dict-ref-id (prep-dtd-arg hashmap-ref)
     dict-ref/default-id (prep-dtd-arg hashmap-ref/default)
     dict-set-id (prep-dtd-arg hashmap-set)
     dict-set!-id (prep-dtd-arg hashmap-set!)
     dict-adjoin-id (prep-dtd-arg hashmap-adjoin)
     dict-adjoin!-id (prep-dtd-arg hashmap-adjoin!)
     dict-delete-id (prep-dtd-arg hashmap-delete)
     dict-delete!-id (prep-dtd-arg hashmap-delete!)
     dict-delete-all-id (prep-dtd-arg hashmap-delete-all)
     dict-delete-all!-id (prep-dtd-arg hashmap-delete-all!)
     dict-replace-id (prep-dtd-arg hashmap-replace)
     dict-replace!-id (prep-dtd-arg hashmap-replace!)
     dict-intern-id (prep-dtd-arg hashmap-intern)
     dict-intern!-id (prep-dtd-arg hashmap-intern!)
     dict-update-id (prep-dtd-arg hashmap-update)
     dict-update!-id (prep-dtd-arg hashmap-update!)
     dict-update/default-id (prep-dtd-arg hashmap-update/default)
     dict-update/default!-id (prep-dtd-arg hashmap-update!/default)
     dict-pop-id (prep-dtd-arg hashmap-pop)
     dict-pop!-id (prep-dtd-arg hashmap-pop!)
     dict-filter-id (prep-dtd-arg hashmap-filter)
     dict-filter!-id (prep-dtd-arg hashmap-filter!)
     dict-remove-id (prep-dtd-arg hashmap-remove)
     dict-remove!-id (prep-dtd-arg hashmap-remove!)
     dict-search-id (prep-dtd-arg hashmap-search)
     dict-search!-id (prep-dtd-arg hashmap-search!)
     dict-copy-id (prep-dtd-arg hashmap-copy)
     dict-size-id (prep-dtd-arg hashmap-size)
     dict-for-each-id (prep-dtd-arg hashmap-for-each)
     dict-count-id (prep-dtd-arg hashmap-count)
     dict-keys-id (prep-dtd-arg hashmap-keys)
     dict-values-id (prep-dtd-arg hashmap-values)
     dict-entries-id (prep-dtd-arg hashmap-entries)
     dict-fold-id (prep-dtd-arg hashmap-fold)
     dict-map->list-id (prep-dtd-arg hashmap-map->list)
     dict->alist-id (prep-dtd-arg hashmap->alist)
     dict-comparator-id (prep-dtd-arg hashmap-key-comparator))))
