(define mapping-dtd
  (let ()

    (define (prep-dtd-arg proc)
      (lambda (dtd . args)
        (apply proc args)))

    (make-dtd
     make-dictionary-id (prep-dtd-arg mapping)
     dictionary?-id (prep-dtd-arg mapping?)
     dict-empty?-id (prep-dtd-arg mapping-empty?)
     dict-contains?-id (prep-dtd-arg mapping-contains?)
     dict-ref-id (prep-dtd-arg mapping-ref)
     dict-ref/default-id (prep-dtd-arg mapping-ref/default)
     dict-set-id (prep-dtd-arg mapping-set)
     dict-set!-id (prep-dtd-arg mapping-set!)
     dict-adjoin-id (prep-dtd-arg mapping-adjoin)
     dict-adjoin!-id (prep-dtd-arg mapping-adjoin!)
     dict-delete-id (prep-dtd-arg mapping-delete)
     dict-delete!-id (prep-dtd-arg mapping-delete!)
     dict-delete-all-id (prep-dtd-arg mapping-delete-all)
     dict-delete-all!-id (prep-dtd-arg mapping-delete-all!)
     dict-replace-id (prep-dtd-arg mapping-replace)
     dict-replace!-id (prep-dtd-arg mapping-replace!)
     dict-intern-id (prep-dtd-arg mapping-intern)
     dict-intern!-id (prep-dtd-arg mapping-intern!)
     dict-update-id (prep-dtd-arg mapping-update)
     dict-update!-id (prep-dtd-arg mapping-update!)
     dict-update/default-id (prep-dtd-arg mapping-update/default)
     dict-update/default!-id (prep-dtd-arg mapping-update!/default)
     dict-pop-id (prep-dtd-arg mapping-pop)
     dict-pop!-id (prep-dtd-arg mapping-pop!)
     dict-filter-id (prep-dtd-arg mapping-filter)
     dict-filter!-id (prep-dtd-arg mapping-filter!)
     dict-remove-id (prep-dtd-arg mapping-remove)
     dict-remove!-id (prep-dtd-arg mapping-remove!)
     dict-search-id (prep-dtd-arg mapping-search)
     dict-search!-id (prep-dtd-arg mapping-search!)
     dict-copy-id (prep-dtd-arg mapping-copy)
     dict-size-id (prep-dtd-arg mapping-size)
     dict-for-each-id (prep-dtd-arg mapping-for-each)
     dict-count-id (prep-dtd-arg mapping-count)
     dict-keys-id (prep-dtd-arg mapping-keys)
     dict-values-id (prep-dtd-arg mapping-values)
     dict-entries-id (prep-dtd-arg mapping-entries)
     dict-fold-id (prep-dtd-arg mapping-fold)
     dict-map->list-id (prep-dtd-arg mapping-map->list)
     dict->alist-id (prep-dtd-arg mapping->alist)
     dict-comparator-id (prep-dtd-arg mapping-key-comparator))))
